### PR TITLE
refactor relay selector to imporve UX/UI

### PR DESCRIPTION
**Pull request by ahonn**
Based on https://github.com/digi-monkey/flycat-web/issues/396 and https://github.com/digi-monkey/flycat-web/issues/389, refactoring the RelaySelector component can bring a better UX/UI and gradually improve code quality.

For this purpose, we need to do two things:
- [x] Avoid relying on the antd's `Cascader` component, build a shared Cascader component for a better UX experience
   - [x] Build a basic cascader component by using Radix UI and TailwindCSS
   - [x] Use Storybook to help the development of shared components
   - [x] Use the new design system style and add it to the TailwindCSS config 
   - [x] Improve the functionality of cascader to meet the requirements of the RelaySelector component
- [x] Refactor the RelaySelector component while keeping the logic unchanged
   - [x] Show relay groups in the cascader
   - [x] Update status after switch relay groups
   - [x] Redirect to relay manager when click "Manage Relays..." option   
   - [x] Improve RelaySelector style on default layout and mobile layout

### CODE REVIEW

**Comment by ahonn** [comment]
@digi-monkey This PR is ready for you to review for now, feel free to report bugs/issues when you review the code or preview deployment.

**Comment by digi-monkey** [comment]
image
the only bug I found is this z-index thing in mobile mode, otherwise it seems perfect and much better than the original antd thing

**Comment by ahonn** [comment]
> image
> @ahonn the only bug I found is this z-index thing in mobile mode, otherwise it seems perfect and much better than the original antd thing

I also found this bug, after some dig I found that the z-index in the project is not well managed and there are many different values. I will try to solve this problem separately and then propose a PR to deal with the z-index issue.

**Comment by digi-monkey** [comment]
> > image
> > @ahonn the only bug I found is this z-index thing in mobile mode, otherwise it seems perfect and much better than the original antd thing
> 
> I also found this bug, after some dig I found that the z-index in the project is not well managed and there are many different values. I will try to solve this problem separately and then propose a PR to deal with the z-index issue.

sounds reasonable

**Review by digi-monkey — APPROVED** [review]

**Pull request merged**
